name: Deploy Staging CI/CD

on:
  pull_request:
    types: [ labeled ]
    branches: [ master ]

jobs:
  ci:
    if: contains(github.event.pull_request.labels.*.name, 'staging')

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js version 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm ci
    - run: npm run build
    - run: npm test
