name: Deploy Staging CI/CD

env:
  S3_BUCKET: next-ebs/staging
  EB_APPLICATION_NAME: next-ebs
  EB_ENVIRONMENT_NAME: NextEbs-Staging
  AWS_REGION: ap-southeast-1

on:
  pull_request:
    types: [labeled]
    branches: [master]

jobs:
  ci:
    if: contains(github.event.pull_request.labels.*.name, 'staging')

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js version 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Install Dependencies
      run: npm ci

    - name: Run build
      run: npm run build

    - name: Run test
      run: npm test

    - name: Upload Built Artifact
      uses: actions/upload-artifact@master
      with:
        name: built artifacts
        path: .next

  cd:
    needs: ci

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Download Built Artifact
        uses: actions/download-artifact@master
        with:
          name: built artifacts
          path: .next

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
          
      - name: Upload assets to S3 Bucket (CDN)
        run: |
          aws s3 sync ./.next s3://next-ebs-cdn-staging/_next
          aws s3 sync ./src/public s3://next-ebs-cdn-staging/public
    
      - name: Zip built files
        run: zip -r staging-${{ github.sha }}.zip . -x **/.git/**/* **/node_modules/**/
      
      - name: Upload Zip file to S3
        run: aws s3 cp staging-${{ github.sha }}.zip s3://next-ebs/staging/

      - name: Create new Elastic Beanstalk Application Version
        run: |
          aws elasticbeanstalk create-application-version \
          --application-name ${{ env.EB_APPLICATION_NAME }} \
          --source-bundle S3Bucket="next-ebs/staging",S3Key="staging-${{ github.sha }}.zip" \
          --version-label "staging-${{ github.sha }}.zip" \
          --description "staging-${{ github.sha }}.zip"
 
      - name: Deploy to Staging
        run: aws elasticbeanstalk update-environment --environment-name NextEbs-Staging --version-label staging-${{ github.sha }}.zip
