name: Test Lighthouse

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
  
    - name: Run Lighthouse on urls and validate with lighthouserc
      with:
        urls: 'https://exterkamp.codes/'
        runs: 3
        budgetPath: '.github/lighthouse/budget.json'
        uploadArtifacts: true
