name: Release

on:
  push:
    branches: master

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Install Dependencies
      run: npm ci

    - name: Run Test
      run: npm test

    - name: Run Build
      run: npm run build

    - name: Add Semantic Release
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: npx semantic-release

